theme: jekyll-theme-minimal
title: [Welcome to my site]
description: [I am a person very committed to my work and attracted to new challenges so I consider myself dynamic and innovative.]
logo: [https://raw.githubusercontent.com/MParvin/MParvin/master/mparvin-logo.png]
google_analytics: [UA-133425298-1]
